### ISSUE TITLE
domain

### ISSUE THREAD

**Issue by peterVG** [orcfax/glossary#1]
definition: A domain is the targeted subject area for a software-intensive system. It is the sphere of knowledge and activity around which the software's processes, rules, and data revolves.

**Comment by peterVG** [comment]
I'm not happy with this current definition. I have lots of good ideas about how to improve it. Here are some now...

**Comment by ross-spencer** [comment]
Closed via https://github.com/orcfax/glossary/commit/f1348da63f19d80881c229b61361f3d4da5359d0
