### ISSUE TITLE
validator

### ISSUE THREAD

**Issue by ross-spencer** [orcfax/glossary#13]
narrower term: Orcfax federated validator
narrower term: Cardano validator (script)
broader term: blockchain validator, i.e. commits new blocks to the chain: https://docs.tendermint.com/v0.34/tendermint-core/validators.html
narrower term: Orcfax validator node
broader term: Individual who is an Orcfax validator license holder, i.e. has purchased an Orcfax license and holds it in their Cardano wallet.

**Comment by waalge** [comment]
Not sure. Think this is more like disambiguation than broader and narrower. But I'm new to SKOS

**Comment by ross-spencer** [comment]
happy to go with whichever you feel. one thing seems clear, there are a decent number of uses of validator!

**Comment by ross-spencer** [comment]
Closed via https://github.com/orcfax/glossary/commit/f1348da63f19d80881c229b61361f3d4da5359d0
