### ISSUE TITLE
arweave

### ISSUE THREAD

**Issue by ross-spencer** [orcfax/glossary#18]
a decentralized (layer-zero) storage network that provides replication of data over hundreds of Arweave nodes and is funded by the Ar token.

**Comment by ross-spencer** [comment]
related term: arweave transaction ID

Another Tx ID used in Orcfax's pipeline/workflow.

https://github.com/ArweaveTeam/arweave-js/blob/master/README.md#transactions

> The transaction ID is a hash of the transaction signature, so a transaction ID can't be known until its contents are finalised and it has been signed.

**Comment by genieck** [comment]
I have no faith in you, I have no faith in Facebook I have no faith in Google I have no faith in IPFS. 

If you do not provide are we dollars for me to watch all of the information that I want into our weave I will let you into IPFS and I will let you into NNTP. 

I will fork or weave and I will put you in the f****** broke house 

You asleep on the streets

**Comment by genieck** [comment]
> a decentralized (layer-zero) storage network that provides replication of data over hundreds of Arweave nodes and is funded by the Ar token.

He a product is too expensive for me, I have a very philanthropic cause and you and I both have not enough philanthropic support 

The world is not good enough for us and we are not giving it what it needs to become good enough 

I simply need to verify that my name and all of the information I etched into an NTP is still available on all that binaries.test and I will be happy enough etching the rest of what I have for the $10 it cost to put whatever I want to have your penultimate ultimate whatever I want on NNTP 

> Ok which is safer than you and safer than Facebook and safer than Google

**Comment by ross-spencer** [comment]
Closed via https://github.com/orcfax/glossary/commit/f1348da63f19d80881c229b61361f3d4da5359d0
