### ISSUE TITLE
feed

### ISSUE THREAD

**Issue by waalge** [orcfax/glossary#2]
definition: An Orcfax feed consists of a <feed_type>/<feed_name>/<feed_version>
eg `cp/ADA-USD/3`

The first two values combined (including the trailing slash as terminator) denote the unique ID for that feed within the Orcfax oracle network.

Integrators will use a substring match in their scripts to check for the existence of feed type and feed name, e.g.  cp/ada-usd/ 

-----
Related: 

+ feed id 
+ versioned feed id 

More distantly related:

+ trigger

**Comment by waalge** [comment]
some context: https://github.com/orcfax/issues/issues/173#issuecomment-2158497854

**Comment by ross-spencer** [comment]
Via discussions today: an identifier for a unique Orcfax data pipeline, e.g.

details such as:

* cex or dex or  both,
* median calculation or something else,
* datum format,
* other details TBD.

**Comment by ross-spencer** [comment]
Closed via https://github.com/orcfax/glossary/commit/f1348da63f19d80881c229b61361f3d4da5359d0
