### ISSUE TITLE
oracle problem

### ISSUE THREAD

**Issue by ross-spencer** [orcfax/glossary#22]
the challenge of providing security, authenticity, and trust, to information brought onto a blockchain by an oracle, i.e. security, authenticity, and trust, of information in a decentralized application.

narrower term: oracle

**Comment by ross-spencer** [comment]
narrower term: price oracle

e.g. providing the price of ada-usd on-chain, versus, a measurement of the relative humidity of a storage facility at given intervals.

**Comment by Christian-MK** [comment]
```
@prefix : <http://glossary.orcfax.io/#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
:oracleProblem
    skos:prefLabel "oracle problem"@en;
    skos:definition '''
      The challenge of providing security, authenticity, and
      trust, to information brought onto a blockchain in a
      decentralized manner.
    ''' ;
    skos:related :oracle.
```

**Comment by ross-spencer** [comment]
+1
