### ISSUE TITLE
CER - incorrect naming convention?

### ISSUE THREAD

**Issue by gchartier** [orcfax/glossary#30]
In the current `CER` glossary term [it states the order is quote first and then base](https://github.com/orcfax/glossary/blob/141b89cec37c3dbad1467b20ef3ca320b63b2301/content/cer.ttl#L11C7-L12C112):
> For a feed of CER type, the feed name naming convention is `{{cur-a}}-{{curr-b}}`, where the ordering follows the forex convention of 'base currency second' (see [base-quote](#baseQuote)).

However, in both the current `base-quote` glossary term and [the forex link referenced below it](https://tradenation.com/articles/base-currency-and-quote-currency/), [it states the order is base first and then quote](https://github.com/orcfax/glossary/blob/141b89cec37c3dbad1467b20ef3ca320b63b2301/content/baseQuote.ttl#L6C7-L7):
> In the forex market, currencies are always traded in pairs; the first is the base currency, and the second is the quoted currency.

I think we need to update the definition of `CER` unless I'm missing something?

**Comment by Christian-MK** [comment]
This is discussed in this branch https://github.com/orcfax/glossary/pull/29#discussion_r1684571105
and settling on [this](https://www.forextime.com/education/videos/what-is-base-and-quote-currencies#:~:text=In%20forex%2C%20currencies,the%20second%20currency.) definition where it's `{{base-currency}}-{{quote-currency}}`
