### ISSUE TITLE
source data point

### ISSUE THREAD

**Issue by Christian-MK** [orcfax/glossary#32]
From peter in [discord](https://discord.com/channels/918870284331802674/1139271976154832916/1265621200994963551)
preferred label: Source data point
definition: An access point from which data may be collected, including APIs, feeds, online locations where datasets are available for download, or data capturing devices such a smartphone.

**Comment by Christian-MK** [comment]
This feel ambiguous or not accurate. When I read "source data point", what comes to mind is an instance/specific data from a source.

As is, the above does not seem to meaningfully separate itself from "data source"

**Comment by ross-spencer** [comment]
maybe: _triangulated data point?_

**Comment by Christian-MK** [comment]
```
@prefix : <http://glossary.orcfax.io/#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
:sourceDataPoint
    skos:prefLabel "source data point"@en;
    skos:definition '''
      The value of a data source, or primary data source, query
      which is embedded in that data source's response to a
      given query.
    ''' ;
    skos:related ex1:dataSource ;
    skos:related ex2:primaryDataSource.
```

**Comment by Christian-MK** [comment]
> maybe: _triangulated data point?_

created a new issue for this
https://github.com/orcfax/glossary/issues/39

**Comment by ross-spencer** [comment]
> The target value of a data source or primary data source query, which is embedded in the response.

maybe:

> the value of a data source or primary data source query that is embedded in that data source's response to a given query

**Comment by Christian-MK** [comment]
> the value of a data source or primary data source query that is embedded in that data source's response to a given query

added
