### ISSUE TITLE
Blockchain oracle

### ISSUE THREAD

**Issue by Christian-MK** [orcfax/glossary#34]
preferred label: Blockchain oracle
definition: A system which connects blockchains to external systems, thereby enabling smart contracts to execute based upon inputs and outputs from the real world.

reference: https://chain.link/education/blockchain-oracles

**Comment by ross-spencer** [comment]
Connected to https://github.com/orcfax/glossary/issues/34

**Comment by Christian-MK** [comment]
```
@prefix : <http://glossary.orcfax.io/#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
:blockchainOracle
    skos:prefLabel "blockchain oracle"@en;
    skos:definition '''
      Software which gathers data from sources in order
      to provide access to entities which require the data to
      execute business logic on top of a blockchain.

      In the context of the oracle problem, Orcfax has
      determined that a blockchain oracle must also be defined
      as an information management system that, in the regular
      course of business, organizes and contextualizes the
      information which it publishes on-chain so that historical
      decisions relating to that information may be audited and
      analyzed.
    ''' ;
    skos:related :oracleProblem.
```

**Comment by ross-spencer** [comment]
I really like the second part of this statement! 

I wonder if between oracle problem/oracle/blockchain oracle we maybe have one term too many? -- does an oracle exist anywhere outside of blockchains yet?

**Comment by Christian-MK** [comment]
> does an oracle exist anywhere outside of blockchains yet?

For some reason I was convinced there was, but now I'm not finding anything useful. Lets remove this broader term for now.
