### ISSUE TITLE
Feed data

### ISSUE THREAD

**Issue by Christian-MK** [orcfax/glossary#36]
Coming out of a review of existing glossary terms, specifically `Feed`
```ttl
    skos:definition '''
        A data pipeline handling time series data.

        The term is also used to refer to the output of a feed.
#        Seems like we should make a distinction between feed and its output (eg feedData?)
```

**Comment by Christian-MK** [comment]
The essence of this already captured in https://github.com/orcfax/glossary/issues/32 ?
Perhaps not, that refers to the value returned by a source when queried whereas this term is trying to define the data which is published on-chain (i.e. the product/result of a funded feed > a Fact Statement ?)

**Comment by ross-spencer** [comment]
This does seem like it might be redundant for now, we could always come back to it?
