### ISSUE TITLE
Consumer

### ISSUE THREAD

**Issue by Christian-MK** [orcfax/glossary#37]
A discussion being moved out of https://github.com/orcfax/glossary/pull/29#discussion_r1684187311
The current entry for Consumer is as follows
```ttl
@prefix : <http://glossary.orcfax.io/#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
:consumer
    skos:prefLabel "consumer"@en;
    skos:definition '''
      Someone who might read the output of an Orcfax datum but
      not necessarily integrate it, see
      [integrator](#integrator).
    ''' ;
    skos:related "integrator".
```
From @waalge 
> Sorry - I disagree with my own definition.
It is literally "someone how 'consumes' an orcfax statement"
>
> So maybe somehting like "someone how 'consumes' an orcfax statement. It is likely they are a participant in a tx in which orcfax data is used. It is therefore likely they have an interest in the orcfax protocol, in particular feed definition and data traceability. A consumer is not necessarily technical, and documentation should be aimed appropriately."

Response from @ross-spencer 
> It is likely they are a participant in a tx in which orcfax data is used.
>
>> Not sure why it is likely? (Cerra used it as a data API first) 
>
> A consumer is not necessarily technical, and documentation should be aimed appropriately.:
>
>> Is this part of the definition you want or just some additional thinking/context? (if former, I'm not sure it should be))

**Comment by waalge** [comment]
I think I introduced the term "consumer"

https://github.com/orcfax/waalge-coop/blob/main/docs/proposal.md#oracles

Correct me if it already existed 

For me, it is someone with skin in the game. They are not simply a "browser" or "window shopper". They are our clients directly or indirectly. (And eventually, somehow, directly or indirectly) they pay us.

**Comment by waalge** [comment]
If we want a term for people who are only browsing our on-chain feeds, can we make that distinct?

Yes - I think its helpful to profile our users in order to make sure our product(s) are effectively targeted

**Comment by ross-spencer** [comment]
> For me, it is someone with skin in the game. They are not simply a "browser" or "window shopper". They are our clients directly or indirectly. (And eventually, somehow, directly or indirectly) they pay us.

Consumer has always existed in some form or another, just not strongly defined. 

I usually use consumer to mean someone or something capable of understanding the data from our feed. 

If there's skin in the game at all then they're an integrator (or partner?) the relationship is, or will be, much more connected than consumer.

**Comment by waalge** [comment]
(For me) An integrator is someone who is doing the integration: They are a dapp developer. Technical. Needs to know the details of how orcfax works and ensure they are integrating oracles correctly.

This is distinct from a consumer: a user of a dapp that uses orcfax. Assumed non-techinical. For example they have a collateralized loan. If orcfax publishes some bad statements like "ada-usd is 1,000,000 : 1", they'll be liquidated. This is their skin in the game. 

A browser: Takes an interest in orcfax. Has no skin in the game.

**Comment by Christian-MK** [comment]
The definition for integrator
```
skos:definition '''
    A developer that builds the use of Orcfax datum into their smart contract and transactions. 
    '''
```

I propose this for consumer:
```
@prefix : <http://glossary.orcfax.io/#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
:consumer
    skos:prefLabel "consumer"@en;
    skos:definition '''
      A participant, either directly or
      indirectly, in a transaction within which orcfax data is
      used.

      Example:
      the user of a lending platform which has integrated Orcfax
      feeds is a consumer.
    ''' ;
    skos:related :integrator .
```

**Comment by waalge** [comment]
This aligns with how i use the term.

I would shorten this slightly 
> ~~An entity that is a~~ A participant ...

**Comment by ross-spencer** [comment]
+1
