### ISSUE TITLE
function

### ISSUE THREAD

**Issue by peterVG** [orcfax/glossary#5]

**Comment by peterVG** [comment]
DM: "Function" in the software world is something that takes inputs and returns outputs. "Function" as a synonym for "use", is correct and "use" does not have the former meaning.

**Comment by Christian-MK** [comment]
```
@prefix : <http://glossary.orcfax.io/#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
:function
    skos:prefLabel "function"@en;
    skos:definition '''
      A distinct and self-contained unit of code that
      accomplishes a specific task using given inputs to
      generate a predictable output. 
    ''' .
```

**Comment by ross-spencer** [comment]
> A distinct, and self contained, piece of code that accomplishes a specific task by taking inputs and returning outputs. 

Not bad, perhaps:

> A distinct and self-contained unit of code that accomplishes a specific task using given inputs to generate a predictable output.

See also clean-code single responsibility principle: https://blog.cleancoder.com/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html

We might also want to differentiate between:

function (mathematics)
function (code)

**Comment by Christian-MK** [comment]
def updated 

> We might also want to differentiate between:
> 
> function (mathematics) function (code)

I wonder if the mention of code in the definition makes this explicit enough?

**Comment by ross-spencer** [comment]
> I wonder if the mention of code in the definition makes this explicit enough?

ah, yep! good enough for me!
