### ISSUE TITLE
datum

### ISSUE THREAD

**Issue by peterVG** [orcfax/glossary#6]
datum: [as understood in math and info science]
Cardano datum: [ find definition at https://docs.cardano.org/]?
Orcfax datum: (from Orcfax Datum Overview) the Cardano inline datum provides a reference input to a Cardano transaction to enable integrator smart contracts to perform some action.

**Comment by ross-spencer** [comment]
Connected to: https://github.com/orcfax/glossary/issues/7

**Comment by ross-spencer** [comment]
Closed via https://github.com/orcfax/glossary/commit/f1348da63f19d80881c229b61361f3d4da5359d0
